const state={data:null,filter:'all',query:''};
const $=s=>document.querySelector(s);
const fmt=n=>Number.isFinite(Number(n))?Number(n).toFixed(2):'—';
const labels={'bottom-fishing':'Bottom','next':'Next','ryan-original':'Ryan','kell-3x-rvol':'Kell'};
const label=s=>labels[s]||s;
function normalizeBars(rows){return(rows||[]).map(r=>Array.isArray(r)?{time:r[0],open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]}:{time:r.time||r.date,open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:+(r.volume||0)}).filter(r=>[r.open,r.high,r.low,r.close].every(Number.isFinite));}
function avg(values,n,ema=false){let out=[],sum=0,cur=values[0]||0,w=2/(n+1);values.forEach((v,i)=>{if(ema){cur=i?v*w+cur*(1-w):v;out.push(i+1>=n?cur:null)}else{sum+=v;if(i>=n)sum-=values[i-n];out.push(i+1>=n?sum/n:null)}});return out;}
function draw(canvas,rows,large=false){const bars=normalizeBars(rows).slice(large?-504:-180);const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.max(1,rect.width*dpr);canvas.height=Math.max(1,rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);if(bars.length<2){ctx.fillStyle='#8ea0b7';ctx.fillText('Chart data unavailable',12,22);return;}const top=12,bottom=large?36:24,left=6,right=8;const lo=Math.min(...bars.map(b=>b.low)),hi=Math.max(...bars.map(b=>b.high)),range=Math.max(hi-lo,.0001);const x=i=>left+i*(w-left-right)/(bars.length-1);const y=v=>top+(hi-v)*(h-top-bottom)/range;ctx.strokeStyle='#1c2d43';ctx.lineWidth=1;for(let i=1;i<4;i++){const yy=top+i*(h-top-bottom)/4;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke()}const closes=bars.map(b=>b.close),e10=avg(closes,10,true),e20=avg(closes,20,true),s50=avg(closes,50,false);const candleW=Math.max(1,Math.min(5,(w-left-right)/bars.length*.7));bars.forEach((b,i)=>{const xx=x(i),up=b.close>=b.open;ctx.strokeStyle=up?'#35d78b':'#ff6d7a';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(b.high));ctx.lineTo(xx,y(b.low));ctx.stroke();const yy=Math.min(y(b.open),y(b.close)),bh=Math.max(1,Math.abs(y(b.open)-y(b.close)));ctx.fillRect(xx-candleW/2,yy,candleW,bh)});[[e10,'#e9bd62'],[e20,'#56a8ff'],[s50,'#a67cff']].forEach(pair=>{const series=pair[0],color=pair[1];ctx.strokeStyle=color;ctx.lineWidth=1.3;ctx.beginPath();let started=false;series.forEach((v,i)=>{if(v==null)return;const xx=x(i),yy=y(v);if(!started){ctx.moveTo(xx,yy);started=true}else ctx.lineTo(xx,yy)});ctx.stroke()});if(large){ctx.fillStyle='#8ea0b7';ctx.fillText('EMA10 / EMA20 / SMA50 · '+bars.length+' sessions',10,h-10)}}
function badges(item){return item.sources.map(s=>'<span class="badge '+(s.startsWith('kell')?'kell':'')+'">'+label(s)+'</span>').join('')}
function visible(item){if(state.query&&!item.ticker.includes(state.query))return false;if(state.filter==='all')return true;if(state.filter==='action')return String((item.analysis||{}).status||'').toUpperCase()==='ACTION';return item.sources.includes(state.filter)}
function card(item){const m=item.metrics||{},status=String((item.analysis||{}).status||'REVIEW').toUpperCase();return '<article class="card" tabindex="0" data-ticker="'+item.ticker+'"><div class="card-head"><div class="ticker">'+item.ticker+'</div><div class="badges">'+badges(item)+'</div></div><div class="metrics"><span>Px <b>'+fmt(m.price)+'</b></span><span>RVOL <b>'+fmt(m.rvol)+'x</b></span><span>RSI <b>'+fmt(m.rsi14)+'</b></span><span>RS <b>'+fmt(m.rs)+'</b></span></div><canvas aria-label="'+item.ticker+' chart"></canvas><div class="analysis-strip"><span>'+(m.setup||'—')+'</span><strong class="'+(status==='ACTION'?'action':status==='WATCH'?'watch':'')+'">'+status+'</strong></div></article>'}
function render(){if(!state.data)return;const items=state.data.candidates.filter(visible);$('#grid').innerHTML=items.map(card).join('');$('#status').textContent=items.length+' / '+state.data.candidateCount+' kandidata';document.querySelectorAll('.card').forEach(cardEl=>{const item=state.data.candidates.find(x=>x.ticker===cardEl.dataset.ticker);draw(cardEl.querySelector('canvas'),item.chartBars);const open=()=>show(item);cardEl.addEventListener('click',open);cardEl.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});}
function show(item){const m=item.metrics||{},a=item.analysis||{};$('#detailBody').innerHTML='<div class="detail-head"><h2>'+item.ticker+'</h2><div class="badges">'+badges(item)+'</div></div><canvas class="detail-chart"></canvas><div class="detail-grid"><div class="fact"><span>Setup</span>'+(m.setup||'—')+'</div><div class="fact"><span>Status analize</span>'+(a.status||'REVIEW')+'</div><div class="fact"><span>RVOL</span>'+fmt(m.rvol)+'x</div><div class="fact"><span>RSI14</span>'+fmt(m.rsi14)+'</div><div class="fact"><span>50D slope</span>'+(m.slope50||'—')+'</div><div class="fact"><span>30W slope</span>'+(m.slope30w||'—')+'</div></div><div class="analysis-text">'+(a.summary||a.analysis||'AI analiza još nije upisana za ovaj dnevni snapshot. Grid i tehnički podaci su dostupni; Work task će ovdje zapisivati dnevni review.')+'</div>';$('#detail').showModal();requestAnimationFrame(()=>draw($('#detailBody canvas'),item.chartBars,true));}
$('#closeDetail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});$('#search').addEventListener('input',e=>{state.query=e.target.value.trim().toUpperCase();render()});$('#filters').addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;state.filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()});
fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(data=>{state.data=data;$('#runMeta').textContent=(data.source&&data.source.sessionDate||'—')+' · Unified '+(data.source&&data.source.runId||'—')+' · read-only';render()}).catch(err=>{$('#status').textContent='Snapshot nije dostupan: '+err.message});
